//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using LandManagement.Entities;
    
    public partial class landmanagementbdEntities : DbContext
    {
        public landmanagementbdEntities()
            : base("name=landmanagementbdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbalquilada> tbalquilada { get; set; }
        public virtual DbSet<tbcarta> tbcarta { get; set; }
        public virtual DbSet<tbcategoriacliente> tbcategoriacliente { get; set; }
        public virtual DbSet<tbcliente> tbcliente { get; set; }
        public virtual DbSet<tbclienteoperacion> tbclienteoperacion { get; set; }
        public virtual DbSet<tbdomicilio> tbdomicilio { get; set; }
        public virtual DbSet<tbenalquiler> tbenalquiler { get; set; }
        public virtual DbSet<tbencuesta> tbencuesta { get; set; }
        public virtual DbSet<tbenventa> tbenventa { get; set; }
        public virtual DbSet<tbmenu> tbmenu { get; set; }
        public virtual DbSet<tboperaciones> tboperaciones { get; set; }
        public virtual DbSet<tbpropiedad> tbpropiedad { get; set; }
        public virtual DbSet<tbprovincia> tbprovincia { get; set; }
        public virtual DbSet<tbreservaalquiler> tbreservaalquiler { get; set; }
        public virtual DbSet<tbreservaventa> tbreservaventa { get; set; }
        public virtual DbSet<tbservicios> tbservicios { get; set; }
        public virtual DbSet<tbsyscliente> tbsyscliente { get; set; }
        public virtual DbSet<tbsyslicencia> tbsyslicencia { get; set; }
        public virtual DbSet<tbsystipocliente> tbsystipocliente { get; set; }
        public virtual DbSet<tbsysversion> tbsysversion { get; set; }
        public virtual DbSet<tbtasacion> tbtasacion { get; set; }
        public virtual DbSet<tbtipofamiliar> tbtipofamiliar { get; set; }
        public virtual DbSet<tbtipopropiedad> tbtipopropiedad { get; set; }
        public virtual DbSet<tbtitulocliente> tbtitulocliente { get; set; }
        public virtual DbSet<tbusuario> tbusuario { get; set; }
        public virtual DbSet<tbventa> tbventa { get; set; }
    }
}
