//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbalquilada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbalquilada()
        {
            this.tboperaciones = new HashSet<tboperaciones>();
        }
    
        public int alq_id { get; set; }
        public System.DateTime alq_fecha_inicio { get; set; }
        public System.DateTime alq_fecha_fin { get; set; }
        public System.DateTime alq_fecha_desocupacion { get; set; }
        public Nullable<double> alq_precio_primero { get; set; }
        public Nullable<double> alq_precio_segundo { get; set; }
        public Nullable<double> alq_precio_tercero { get; set; }
        public Nullable<double> alq_precio_cuarto { get; set; }
        public Nullable<double> alq_precio_quinto { get; set; }
        public Nullable<double> alq_precio_sexto { get; set; }
        public bool alq_servicios_cargo_locador { get; set; }
        public Nullable<bool> alq_pago_administracion { get; set; }
        public Nullable<bool> alq_factura_iva { get; set; }
        public Nullable<bool> alq_pago_deposito { get; set; }
        public string alq_banco { get; set; }
        public string alq_numero_cuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tboperaciones> tboperaciones { get; set; }
    }
}
