//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbalquilada
    {
        #region Primitive Properties
    
        public virtual int alq_id
        {
            get;
            set;
        }
    
        public virtual System.DateTime alq_fecha_inicio
        {
            get;
            set;
        }
    
        public virtual System.DateTime alq_fecha_fin
        {
            get;
            set;
        }
    
        public virtual System.DateTime alq_fecha_desocupacion
        {
            get;
            set;
        }
    
        public virtual Nullable<double> alq_precio_primero
        {
            get;
            set;
        }
    
        public virtual Nullable<double> alq_precio_segundo
        {
            get;
            set;
        }
    
        public virtual Nullable<double> alq_precio_tercero
        {
            get;
            set;
        }
    
        public virtual Nullable<double> alq_precio_cuarto
        {
            get;
            set;
        }
    
        public virtual Nullable<double> alq_precio_quinto
        {
            get;
            set;
        }
    
        public virtual bool alq_servicios_cargo_locador
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> alq_pago_administracion
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> alq_factura_iva
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> alq_pago_deposito
        {
            get;
            set;
        }
    
        public virtual string alq_banco
        {
            get;
            set;
        }
    
        public virtual string alq_numero_cuenta
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<tboperaciones> tboperaciones
        {
            get
            {
                if (_tboperaciones == null)
                {
                    var newCollection = new FixupCollection<tboperaciones>();
                    newCollection.CollectionChanged += Fixuptboperaciones;
                    _tboperaciones = newCollection;
                }
                return _tboperaciones;
            }
            set
            {
                if (!ReferenceEquals(_tboperaciones, value))
                {
                    var previousValue = _tboperaciones as FixupCollection<tboperaciones>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptboperaciones;
                    }
                    _tboperaciones = value;
                    var newValue = value as FixupCollection<tboperaciones>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptboperaciones;
                    }
                }
            }
        }
        private ICollection<tboperaciones> _tboperaciones;

        #endregion

        #region Association Fixup
    
        private void Fixuptboperaciones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tboperaciones item in e.NewItems)
                {
                    item.tbalquilada = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tboperaciones item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbalquilada, this))
                    {
                        item.tbalquilada = null;
                    }
                }
            }
        }

        #endregion

    }
}
