//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbcarta
    {
        #region Primitive Properties
    
        public virtual int car_id
        {
            get;
            set;
        }
    
        public virtual string car_cuerpo
        {
            get;
            set;
        }
    
        public virtual string car_pie
        {
            get;
            set;
        }

        #endregion

    }
}
