//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbclienteoperacion
    {
        public int cli_id { get; set; }
        public int ope_id { get; set; }
        public int stc_id { get; set; }
    
        public virtual tbcliente tbcliente { get; set; }
        public virtual tboperaciones tboperaciones { get; set; }
        public virtual tbsystipocliente tbsystipocliente { get; set; }
    }
}
