//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbcliente()
        {
            this.tbcliente1 = new HashSet<tbcliente>();
            this.tbclienteoperacion = new HashSet<tbclienteoperacion>();
            this.tbdomicilio = new HashSet<tbdomicilio>();
            this.tbpropiedad = new HashSet<tbpropiedad>();
        }
    
        public int cli_id { get; set; }
        public Nullable<int> cli_id_padre { get; set; }
        public int tif_id { get; set; }
        public int ccl_id { get; set; }
        public int tcl_id { get; set; }
        public System.DateTime cli_fecha { get; set; }
        public string cli_nombre { get; set; }
        public string cli_apellido { get; set; }
        public string cli_telefono_celular { get; set; }
        public string cli_telefono_particular { get; set; }
        public string cli_telefono_laboral { get; set; }
        public string cli_email { get; set; }
        public string cli_sexo { get; set; }
        public System.DateTime cli_fecha_nacimiento { get; set; }
        public string cli_nacionalidad { get; set; }
        public string cli_estado_civil { get; set; }
        public string cli_tipo_documento { get; set; }
        public string cli_numero_documento { get; set; }
        public string cli_cuit_cuil { get; set; }
        public string cli_como_llego { get; set; }
        public Nullable<System.DateTime> cli_actualizado { get; set; }
        public string cli_nombre_pila { get; set; }
        public Nullable<bool> cli_imprime_carta { get; set; }
        public string cli_observaciones { get; set; }
        public Nullable<int> cli_id_import { get; set; }
    
        public virtual tbcategoriacliente tbcategoriacliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcliente> tbcliente1 { get; set; }
        public virtual tbcliente tbcliente2 { get; set; }
        public virtual tbtipofamiliar tbtipofamiliar { get; set; }
        public virtual tbtitulocliente tbtitulocliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbclienteoperacion> tbclienteoperacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbdomicilio> tbdomicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbpropiedad> tbpropiedad { get; set; }
    }
}
