//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdomicilio
    {
        public int dom_id { get; set; }
        public int cli_id { get; set; }
        public int tip_id { get; set; }
        public int prv_id { get; set; }
        public string dom_calle { get; set; }
        public int dom_numero { get; set; }
        public Nullable<int> dom_piso { get; set; }
        public string dom_departamento { get; set; }
        public string dom_codigo_postal { get; set; }
        public string dom_localidad { get; set; }
        public bool dom_actual { get; set; }
        public string dom_domicilio_importado { get; set; }
    
        public virtual tbcliente tbcliente { get; set; }
        public virtual tbprovincia tbprovincia { get; set; }
        public virtual tbtipopropiedad tbtipopropiedad { get; set; }
    }
}
