//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbenventa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbenventa()
        {
            this.tboperaciones = new HashSet<tboperaciones>();
        }
    
        public int env_id { get; set; }
        public System.DateTime env_fecha_vencimiento { get; set; }
        public double env_precio { get; set; }
        public string env_cartel { get; set; }
        public string env_observaciones { get; set; }
        public bool env_titulo_propiedad { get; set; }
        public bool env_planos { get; set; }
        public bool env_reglamento { get; set; }
        public bool env_matricula { get; set; }
        public bool env_abl { get; set; }
        public bool env_agua { get; set; }
        public bool env_luz { get; set; }
        public bool env_gas { get; set; }
        public bool env_telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tboperaciones> tboperaciones { get; set; }
    }
}
