//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbenalquiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbenalquiler()
        {
            this.tboperaciones = new HashSet<tboperaciones>();
        }
    
        public int ena_id { get; set; }
        public Nullable<double> ena_precio_primer_anio { get; set; }
        public Nullable<double> ena_precio_segundo_anio { get; set; }
        public Nullable<double> ena_precio_tercer_anio { get; set; }
        public Nullable<double> ena_precio_cuarto_anio { get; set; }
        public Nullable<double> ena_precio_quinto_anio { get; set; }
        public Nullable<double> ena_expensas { get; set; }
        public Nullable<double> ena_abl { get; set; }
        public Nullable<double> ena_aguas { get; set; }
        public Nullable<double> ena_luz { get; set; }
        public Nullable<double> ena_gas { get; set; }
        public Nullable<double> ena_telefono { get; set; }
        public string ena_observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tboperaciones> tboperaciones { get; set; }
    }
}
