//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tboperaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tboperaciones()
        {
            this.tbclienteoperacion = new HashSet<tbclienteoperacion>();
        }
    
        public int ope_id { get; set; }
        public int usu_id { get; set; }
        public int pro_id { get; set; }
        public Nullable<int> tas_id { get; set; }
        public Nullable<int> env_id { get; set; }
        public Nullable<int> rev_id { get; set; }
        public Nullable<int> ven_id { get; set; }
        public Nullable<int> ena_id { get; set; }
        public Nullable<int> rea_id { get; set; }
        public Nullable<int> alq_id { get; set; }
        public Nullable<int> enc_id { get; set; }
        public Nullable<System.DateTime> ope_fecha { get; set; }
    
        public virtual tbalquilada tbalquilada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbclienteoperacion> tbclienteoperacion { get; set; }
        public virtual tbenalquiler tbenalquiler { get; set; }
        public virtual tbencuesta tbencuesta { get; set; }
        public virtual tbenventa tbenventa { get; set; }
        public virtual tbpropiedad tbpropiedad { get; set; }
        public virtual tbreservaalquiler tbreservaalquiler { get; set; }
        public virtual tbreservaventa tbreservaventa { get; set; }
        public virtual tbtasacion tbtasacion { get; set; }
        public virtual tbusuario tbusuario { get; set; }
        public virtual tbventa tbventa { get; set; }
    }
}
