//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tboperaciones
    {
        #region Primitive Properties
    
        public virtual int ope_id
        {
            get;
            set;
        }
    
        public virtual int usu_id
        {
            get { return _usu_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_usu_id != value)
                    {
                        if (tbusuario != null && tbusuario.usu_id != value)
                        {
                            tbusuario = null;
                        }
                        _usu_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _usu_id;
    
        public virtual int pro_id
        {
            get { return _pro_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_pro_id != value)
                    {
                        if (tbpropiedad != null && tbpropiedad.pro_id != value)
                        {
                            tbpropiedad = null;
                        }
                        _pro_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _pro_id;
    
        public virtual Nullable<int> tas_id
        {
            get { return _tas_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_tas_id != value)
                    {
                        if (tbtasacion != null && tbtasacion.tas_id != value)
                        {
                            tbtasacion = null;
                        }
                        _tas_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _tas_id;
    
        public virtual Nullable<int> env_id
        {
            get { return _env_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_env_id != value)
                    {
                        if (tbenventa != null && tbenventa.env_id != value)
                        {
                            tbenventa = null;
                        }
                        _env_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _env_id;
    
        public virtual Nullable<int> rev_id
        {
            get { return _rev_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_rev_id != value)
                    {
                        if (tbreservaventa != null && tbreservaventa.rev_id != value)
                        {
                            tbreservaventa = null;
                        }
                        _rev_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _rev_id;
    
        public virtual Nullable<int> ven_id
        {
            get { return _ven_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_ven_id != value)
                    {
                        if (tbventa != null && tbventa.ven_id != value)
                        {
                            tbventa = null;
                        }
                        _ven_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _ven_id;
    
        public virtual Nullable<int> ena_id
        {
            get { return _ena_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_ena_id != value)
                    {
                        if (tbenalquiler != null && tbenalquiler.ena_id != value)
                        {
                            tbenalquiler = null;
                        }
                        _ena_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _ena_id;
    
        public virtual Nullable<int> rea_id
        {
            get { return _rea_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_rea_id != value)
                    {
                        if (tbreservaalquiler != null && tbreservaalquiler.rea_id != value)
                        {
                            tbreservaalquiler = null;
                        }
                        _rea_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _rea_id;
    
        public virtual Nullable<int> alq_id
        {
            get { return _alq_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_alq_id != value)
                    {
                        if (tbalquilada != null && tbalquilada.alq_id != value)
                        {
                            tbalquilada = null;
                        }
                        _alq_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _alq_id;
    
        public virtual Nullable<int> enc_id
        {
            get { return _enc_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_enc_id != value)
                    {
                        if (tbencuesta != null && tbencuesta.enc_id != value)
                        {
                            tbencuesta = null;
                        }
                        _enc_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _enc_id;
    
        public virtual Nullable<System.DateTime> ope_fecha
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual tbalquilada tbalquilada
        {
            get { return _tbalquilada; }
            set
            {
                if (!ReferenceEquals(_tbalquilada, value))
                {
                    var previousValue = _tbalquilada;
                    _tbalquilada = value;
                    Fixuptbalquilada(previousValue);
                }
            }
        }
        private tbalquilada _tbalquilada;
    
        public virtual ICollection<tbclienteoperacion> tbclienteoperacion
        {
            get
            {
                if (_tbclienteoperacion == null)
                {
                    var newCollection = new FixupCollection<tbclienteoperacion>();
                    newCollection.CollectionChanged += Fixuptbclienteoperacion;
                    _tbclienteoperacion = newCollection;
                }
                return _tbclienteoperacion;
            }
            set
            {
                if (!ReferenceEquals(_tbclienteoperacion, value))
                {
                    var previousValue = _tbclienteoperacion as FixupCollection<tbclienteoperacion>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbclienteoperacion;
                    }
                    _tbclienteoperacion = value;
                    var newValue = value as FixupCollection<tbclienteoperacion>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbclienteoperacion;
                    }
                }
            }
        }
        private ICollection<tbclienteoperacion> _tbclienteoperacion;
    
        public virtual tbenalquiler tbenalquiler
        {
            get { return _tbenalquiler; }
            set
            {
                if (!ReferenceEquals(_tbenalquiler, value))
                {
                    var previousValue = _tbenalquiler;
                    _tbenalquiler = value;
                    Fixuptbenalquiler(previousValue);
                }
            }
        }
        private tbenalquiler _tbenalquiler;
    
        public virtual tbencuesta tbencuesta
        {
            get { return _tbencuesta; }
            set
            {
                if (!ReferenceEquals(_tbencuesta, value))
                {
                    var previousValue = _tbencuesta;
                    _tbencuesta = value;
                    Fixuptbencuesta(previousValue);
                }
            }
        }
        private tbencuesta _tbencuesta;
    
        public virtual tbenventa tbenventa
        {
            get { return _tbenventa; }
            set
            {
                if (!ReferenceEquals(_tbenventa, value))
                {
                    var previousValue = _tbenventa;
                    _tbenventa = value;
                    Fixuptbenventa(previousValue);
                }
            }
        }
        private tbenventa _tbenventa;
    
        public virtual tbpropiedad tbpropiedad
        {
            get { return _tbpropiedad; }
            set
            {
                if (!ReferenceEquals(_tbpropiedad, value))
                {
                    var previousValue = _tbpropiedad;
                    _tbpropiedad = value;
                    Fixuptbpropiedad(previousValue);
                }
            }
        }
        private tbpropiedad _tbpropiedad;
    
        public virtual tbreservaalquiler tbreservaalquiler
        {
            get { return _tbreservaalquiler; }
            set
            {
                if (!ReferenceEquals(_tbreservaalquiler, value))
                {
                    var previousValue = _tbreservaalquiler;
                    _tbreservaalquiler = value;
                    Fixuptbreservaalquiler(previousValue);
                }
            }
        }
        private tbreservaalquiler _tbreservaalquiler;
    
        public virtual tbreservaventa tbreservaventa
        {
            get { return _tbreservaventa; }
            set
            {
                if (!ReferenceEquals(_tbreservaventa, value))
                {
                    var previousValue = _tbreservaventa;
                    _tbreservaventa = value;
                    Fixuptbreservaventa(previousValue);
                }
            }
        }
        private tbreservaventa _tbreservaventa;
    
        public virtual tbtasacion tbtasacion
        {
            get { return _tbtasacion; }
            set
            {
                if (!ReferenceEquals(_tbtasacion, value))
                {
                    var previousValue = _tbtasacion;
                    _tbtasacion = value;
                    Fixuptbtasacion(previousValue);
                }
            }
        }
        private tbtasacion _tbtasacion;
    
        public virtual tbusuario tbusuario
        {
            get { return _tbusuario; }
            set
            {
                if (!ReferenceEquals(_tbusuario, value))
                {
                    var previousValue = _tbusuario;
                    _tbusuario = value;
                    Fixuptbusuario(previousValue);
                }
            }
        }
        private tbusuario _tbusuario;
    
        public virtual tbventa tbventa
        {
            get { return _tbventa; }
            set
            {
                if (!ReferenceEquals(_tbventa, value))
                {
                    var previousValue = _tbventa;
                    _tbventa = value;
                    Fixuptbventa(previousValue);
                }
            }
        }
        private tbventa _tbventa;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixuptbalquilada(tbalquilada previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbalquilada != null)
            {
                if (!tbalquilada.tboperaciones.Contains(this))
                {
                    tbalquilada.tboperaciones.Add(this);
                }
                if (alq_id != tbalquilada.alq_id)
                {
                    alq_id = tbalquilada.alq_id;
                }
            }
            else if (!_settingFK)
            {
                alq_id = null;
            }
        }
    
        private void Fixuptbenalquiler(tbenalquiler previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbenalquiler != null)
            {
                if (!tbenalquiler.tboperaciones.Contains(this))
                {
                    tbenalquiler.tboperaciones.Add(this);
                }
                if (ena_id != tbenalquiler.ena_id)
                {
                    ena_id = tbenalquiler.ena_id;
                }
            }
            else if (!_settingFK)
            {
                ena_id = null;
            }
        }
    
        private void Fixuptbencuesta(tbencuesta previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbencuesta != null)
            {
                if (!tbencuesta.tboperaciones.Contains(this))
                {
                    tbencuesta.tboperaciones.Add(this);
                }
                if (enc_id != tbencuesta.enc_id)
                {
                    enc_id = tbencuesta.enc_id;
                }
            }
            else if (!_settingFK)
            {
                enc_id = null;
            }
        }
    
        private void Fixuptbenventa(tbenventa previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbenventa != null)
            {
                if (!tbenventa.tboperaciones.Contains(this))
                {
                    tbenventa.tboperaciones.Add(this);
                }
                if (env_id != tbenventa.env_id)
                {
                    env_id = tbenventa.env_id;
                }
            }
            else if (!_settingFK)
            {
                env_id = null;
            }
        }
    
        private void Fixuptbpropiedad(tbpropiedad previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbpropiedad != null)
            {
                if (!tbpropiedad.tboperaciones.Contains(this))
                {
                    tbpropiedad.tboperaciones.Add(this);
                }
                if (pro_id != tbpropiedad.pro_id)
                {
                    pro_id = tbpropiedad.pro_id;
                }
            }
        }
    
        private void Fixuptbreservaalquiler(tbreservaalquiler previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbreservaalquiler != null)
            {
                if (!tbreservaalquiler.tboperaciones.Contains(this))
                {
                    tbreservaalquiler.tboperaciones.Add(this);
                }
                if (rea_id != tbreservaalquiler.rea_id)
                {
                    rea_id = tbreservaalquiler.rea_id;
                }
            }
            else if (!_settingFK)
            {
                rea_id = null;
            }
        }
    
        private void Fixuptbreservaventa(tbreservaventa previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbreservaventa != null)
            {
                if (!tbreservaventa.tboperaciones.Contains(this))
                {
                    tbreservaventa.tboperaciones.Add(this);
                }
                if (rev_id != tbreservaventa.rev_id)
                {
                    rev_id = tbreservaventa.rev_id;
                }
            }
            else if (!_settingFK)
            {
                rev_id = null;
            }
        }
    
        private void Fixuptbtasacion(tbtasacion previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbtasacion != null)
            {
                if (!tbtasacion.tboperaciones.Contains(this))
                {
                    tbtasacion.tboperaciones.Add(this);
                }
                if (tas_id != tbtasacion.tas_id)
                {
                    tas_id = tbtasacion.tas_id;
                }
            }
            else if (!_settingFK)
            {
                tas_id = null;
            }
        }
    
        private void Fixuptbusuario(tbusuario previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbusuario != null)
            {
                if (!tbusuario.tboperaciones.Contains(this))
                {
                    tbusuario.tboperaciones.Add(this);
                }
                if (usu_id != tbusuario.usu_id)
                {
                    usu_id = tbusuario.usu_id;
                }
            }
        }
    
        private void Fixuptbventa(tbventa previousValue)
        {
            if (previousValue != null && previousValue.tboperaciones.Contains(this))
            {
                previousValue.tboperaciones.Remove(this);
            }
    
            if (tbventa != null)
            {
                if (!tbventa.tboperaciones.Contains(this))
                {
                    tbventa.tboperaciones.Add(this);
                }
                if (ven_id != tbventa.ven_id)
                {
                    ven_id = tbventa.ven_id;
                }
            }
            else if (!_settingFK)
            {
                ven_id = null;
            }
        }
    
        private void Fixuptbclienteoperacion(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbclienteoperacion item in e.NewItems)
                {
                    item.tboperaciones = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbclienteoperacion item in e.OldItems)
                {
                    if (ReferenceEquals(item.tboperaciones, this))
                    {
                        item.tboperaciones = null;
                    }
                }
            }
        }

        #endregion

    }
}
