//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpropiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbpropiedad()
        {
            this.tboperaciones = new HashSet<tboperaciones>();
            this.tbcliente = new HashSet<tbcliente>();
            this.tbservicios = new HashSet<tbservicios>();
        }
    
        public int pro_id { get; set; }
        public int tip_id { get; set; }
        public int prv_id { get; set; }
        public string pro_calle { get; set; }
        public int pro_numero { get; set; }
        public Nullable<int> pro_piso { get; set; }
        public string pro_departamento { get; set; }
        public string pro_codigo_postal { get; set; }
        public string pro_localidad { get; set; }
        public string pro_caracteristica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tboperaciones> tboperaciones { get; set; }
        public virtual tbprovincia tbprovincia { get; set; }
        public virtual tbtipopropiedad tbtipopropiedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcliente> tbcliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbservicios> tbservicios { get; set; }
    }
}
