//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbservicios
    {
        #region Primitive Properties
    
        public virtual int ser_id
        {
            get;
            set;
        }
    
        public virtual string ser_descripcion
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<tbpropiedad> tbpropiedad
        {
            get
            {
                if (_tbpropiedad == null)
                {
                    var newCollection = new FixupCollection<tbpropiedad>();
                    newCollection.CollectionChanged += Fixuptbpropiedad;
                    _tbpropiedad = newCollection;
                }
                return _tbpropiedad;
            }
            set
            {
                if (!ReferenceEquals(_tbpropiedad, value))
                {
                    var previousValue = _tbpropiedad as FixupCollection<tbpropiedad>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbpropiedad;
                    }
                    _tbpropiedad = value;
                    var newValue = value as FixupCollection<tbpropiedad>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbpropiedad;
                    }
                }
            }
        }
        private ICollection<tbpropiedad> _tbpropiedad;

        #endregion

        #region Association Fixup
    
        private void Fixuptbpropiedad(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbpropiedad item in e.NewItems)
                {
                    if (!item.tbservicios.Contains(this))
                    {
                        item.tbservicios.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbpropiedad item in e.OldItems)
                {
                    if (item.tbservicios.Contains(this))
                    {
                        item.tbservicios.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
