//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsyscliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbsyscliente()
        {
            this.tbsyslicencia = new HashSet<tbsyslicencia>();
        }
    
        public int scl_id { get; set; }
        public string scl_nombre { get; set; }
        public string scl_razon_social { get; set; }
        public string scl_calle { get; set; }
        public int scl_numero { get; set; }
        public string scl_localidad { get; set; }
        public string scl_telefono { get; set; }
        public int scl_cantidad_licencias { get; set; }
        public string scl_observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsyslicencia> tbsyslicencia { get; set; }
    }
}
