//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbsyslicencia
    {
        #region Primitive Properties
    
        public virtual int sli_id
        {
            get;
            set;
        }
    
        public virtual int scl_id
        {
            get { return _scl_id; }
            set
            {
                if (_scl_id != value)
                {
                    if (tbsyscliente != null && tbsyscliente.scl_id != value)
                    {
                        tbsyscliente = null;
                    }
                    _scl_id = value;
                }
            }
        }
        private int _scl_id;
    
        public virtual string sli_mac_ethernet
        {
            get;
            set;
        }
    
        public virtual string sli_mac_wifi
        {
            get;
            set;
        }
    
        public virtual string sli_hash_access
        {
            get;
            set;
        }
    
        public virtual bool sli_estado
        {
            get;
            set;
        }
    
        public virtual bool sli_en_uso
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual tbsyscliente tbsyscliente
        {
            get { return _tbsyscliente; }
            set
            {
                if (!ReferenceEquals(_tbsyscliente, value))
                {
                    var previousValue = _tbsyscliente;
                    _tbsyscliente = value;
                    Fixuptbsyscliente(previousValue);
                }
            }
        }
        private tbsyscliente _tbsyscliente;

        #endregion

        #region Association Fixup
    
        private void Fixuptbsyscliente(tbsyscliente previousValue)
        {
            if (previousValue != null && previousValue.tbsyslicencia.Contains(this))
            {
                previousValue.tbsyslicencia.Remove(this);
            }
    
            if (tbsyscliente != null)
            {
                if (!tbsyscliente.tbsyslicencia.Contains(this))
                {
                    tbsyscliente.tbsyslicencia.Add(this);
                }
                if (scl_id != tbsyscliente.scl_id)
                {
                    scl_id = tbsyscliente.scl_id;
                }
            }
        }

        #endregion

    }
}
