//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbsyscliente
    {
        #region Primitive Properties
    
        public virtual int scl_id
        {
            get;
            set;
        }
    
        public virtual string scl_nombre
        {
            get;
            set;
        }
    
        public virtual string scl_razon_social
        {
            get;
            set;
        }
    
        public virtual string scl_calle
        {
            get;
            set;
        }
    
        public virtual int scl_numero
        {
            get;
            set;
        }
    
        public virtual string scl_localidad
        {
            get;
            set;
        }
    
        public virtual string scl_telefono
        {
            get;
            set;
        }
    
        public virtual int scl_cantidad_licencias
        {
            get;
            set;
        }
    
        public virtual string scl_observaciones
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<tbsyslicencia> tbsyslicencia
        {
            get
            {
                if (_tbsyslicencia == null)
                {
                    var newCollection = new FixupCollection<tbsyslicencia>();
                    newCollection.CollectionChanged += Fixuptbsyslicencia;
                    _tbsyslicencia = newCollection;
                }
                return _tbsyslicencia;
            }
            set
            {
                if (!ReferenceEquals(_tbsyslicencia, value))
                {
                    var previousValue = _tbsyslicencia as FixupCollection<tbsyslicencia>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbsyslicencia;
                    }
                    _tbsyslicencia = value;
                    var newValue = value as FixupCollection<tbsyslicencia>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbsyslicencia;
                    }
                }
            }
        }
        private ICollection<tbsyslicencia> _tbsyslicencia;

        #endregion

        #region Association Fixup
    
        private void Fixuptbsyslicencia(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbsyslicencia item in e.NewItems)
                {
                    item.tbsyscliente = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbsyslicencia item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbsyscliente, this))
                    {
                        item.tbsyscliente = null;
                    }
                }
            }
        }

        #endregion

    }
}
