//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsyslicencia
    {
        public int sli_id { get; set; }
        public int scl_id { get; set; }
        public string sli_mac_ethernet { get; set; }
        public string sli_mac_wifi { get; set; }
        public string sli_hash_access { get; set; }
        public bool sli_estado { get; set; }
        public bool sli_en_uso { get; set; }
    
        public virtual tbsyscliente tbsyscliente { get; set; }
    }
}
