//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbtipofamiliar
    {
        #region Primitive Properties
    
        public virtual int tif_id
        {
            get;
            set;
        }
    
        public virtual string tif_descripcion
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<tbcliente> tbcliente
        {
            get
            {
                if (_tbcliente == null)
                {
                    var newCollection = new FixupCollection<tbcliente>();
                    newCollection.CollectionChanged += Fixuptbcliente;
                    _tbcliente = newCollection;
                }
                return _tbcliente;
            }
            set
            {
                if (!ReferenceEquals(_tbcliente, value))
                {
                    var previousValue = _tbcliente as FixupCollection<tbcliente>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbcliente;
                    }
                    _tbcliente = value;
                    var newValue = value as FixupCollection<tbcliente>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbcliente;
                    }
                }
            }
        }
        private ICollection<tbcliente> _tbcliente;

        #endregion

        #region Association Fixup
    
        private void Fixuptbcliente(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbcliente item in e.NewItems)
                {
                    item.tbtipofamiliar = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbcliente item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbtipofamiliar, this))
                    {
                        item.tbtipofamiliar = null;
                    }
                }
            }
        }

        #endregion

    }
}
