//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbtipopropiedad
    {
        #region Primitive Properties
    
        public virtual int tip_id
        {
            get;
            set;
        }
    
        public virtual string tip_descripcion
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<tbdomicilio> tbdomicilio
        {
            get
            {
                if (_tbdomicilio == null)
                {
                    var newCollection = new FixupCollection<tbdomicilio>();
                    newCollection.CollectionChanged += Fixuptbdomicilio;
                    _tbdomicilio = newCollection;
                }
                return _tbdomicilio;
            }
            set
            {
                if (!ReferenceEquals(_tbdomicilio, value))
                {
                    var previousValue = _tbdomicilio as FixupCollection<tbdomicilio>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbdomicilio;
                    }
                    _tbdomicilio = value;
                    var newValue = value as FixupCollection<tbdomicilio>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbdomicilio;
                    }
                }
            }
        }
        private ICollection<tbdomicilio> _tbdomicilio;
    
        public virtual ICollection<tbpropiedad> tbpropiedad
        {
            get
            {
                if (_tbpropiedad == null)
                {
                    var newCollection = new FixupCollection<tbpropiedad>();
                    newCollection.CollectionChanged += Fixuptbpropiedad;
                    _tbpropiedad = newCollection;
                }
                return _tbpropiedad;
            }
            set
            {
                if (!ReferenceEquals(_tbpropiedad, value))
                {
                    var previousValue = _tbpropiedad as FixupCollection<tbpropiedad>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbpropiedad;
                    }
                    _tbpropiedad = value;
                    var newValue = value as FixupCollection<tbpropiedad>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbpropiedad;
                    }
                }
            }
        }
        private ICollection<tbpropiedad> _tbpropiedad;

        #endregion

        #region Association Fixup
    
        private void Fixuptbdomicilio(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbdomicilio item in e.NewItems)
                {
                    item.tbtipopropiedad = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbdomicilio item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbtipopropiedad, this))
                    {
                        item.tbtipopropiedad = null;
                    }
                }
            }
        }
    
        private void Fixuptbpropiedad(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbpropiedad item in e.NewItems)
                {
                    item.tbtipopropiedad = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbpropiedad item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbtipopropiedad, this))
                    {
                        item.tbtipopropiedad = null;
                    }
                }
            }
        }

        #endregion

    }
}
