//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbusuario
    {
        #region Primitive Properties
    
        public virtual int usu_id
        {
            get;
            set;
        }
    
        public virtual string usu_nombre
        {
            get;
            set;
        }
    
        public virtual string usu_apellido
        {
            get;
            set;
        }
    
        public virtual string usu_email
        {
            get;
            set;
        }
    
        public virtual string usu_email_password
        {
            get;
            set;
        }
    
        public virtual string usu_nombre_login
        {
            get;
            set;
        }
    
        public virtual string usu_password
        {
            get;
            set;
        }
    
        public virtual bool usu_estado
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<tboperaciones> tboperaciones
        {
            get
            {
                if (_tboperaciones == null)
                {
                    var newCollection = new FixupCollection<tboperaciones>();
                    newCollection.CollectionChanged += Fixuptboperaciones;
                    _tboperaciones = newCollection;
                }
                return _tboperaciones;
            }
            set
            {
                if (!ReferenceEquals(_tboperaciones, value))
                {
                    var previousValue = _tboperaciones as FixupCollection<tboperaciones>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptboperaciones;
                    }
                    _tboperaciones = value;
                    var newValue = value as FixupCollection<tboperaciones>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptboperaciones;
                    }
                }
            }
        }
        private ICollection<tboperaciones> _tboperaciones;
    
        public virtual ICollection<tbmenu> tbmenu
        {
            get
            {
                if (_tbmenu == null)
                {
                    var newCollection = new FixupCollection<tbmenu>();
                    newCollection.CollectionChanged += Fixuptbmenu;
                    _tbmenu = newCollection;
                }
                return _tbmenu;
            }
            set
            {
                if (!ReferenceEquals(_tbmenu, value))
                {
                    var previousValue = _tbmenu as FixupCollection<tbmenu>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptbmenu;
                    }
                    _tbmenu = value;
                    var newValue = value as FixupCollection<tbmenu>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptbmenu;
                    }
                }
            }
        }
        private ICollection<tbmenu> _tbmenu;

        #endregion
        #region Association Fixup
    
        private void Fixuptboperaciones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tboperaciones item in e.NewItems)
                {
                    item.tbusuario = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tboperaciones item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbusuario, this))
                    {
                        item.tbusuario = null;
                    }
                }
            }
        }
    
        private void Fixuptbmenu(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tbmenu item in e.NewItems)
                {
                    if (!item.tbusuario.Contains(this))
                    {
                        item.tbusuario.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tbmenu item in e.OldItems)
                {
                    if (item.tbusuario.Contains(this))
                    {
                        item.tbusuario.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
