//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LandManagement.Entities
{
    public partial class tbventa
    {
        #region Primitive Properties
    
        public virtual int ven_id
        {
            get;
            set;
        }
    
        public virtual System.DateTime ven_fecha_boleto
        {
            get;
            set;
        }
    
        public virtual System.DateTime ven_fecha_escritura
        {
            get;
            set;
        }
    
        public virtual double ven_precio
        {
            get;
            set;
        }
    
        public virtual string ven_escribano
        {
            get;
            set;
        }
    
        public virtual double ven_presupuesto
        {
            get;
            set;
        }
    
        public virtual string ven_escribania
        {
            get;
            set;
        }
    
        public virtual double ven_cobrado
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<tboperaciones> tboperaciones
        {
            get
            {
                if (_tboperaciones == null)
                {
                    var newCollection = new FixupCollection<tboperaciones>();
                    newCollection.CollectionChanged += Fixuptboperaciones;
                    _tboperaciones = newCollection;
                }
                return _tboperaciones;
            }
            set
            {
                if (!ReferenceEquals(_tboperaciones, value))
                {
                    var previousValue = _tboperaciones as FixupCollection<tboperaciones>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptboperaciones;
                    }
                    _tboperaciones = value;
                    var newValue = value as FixupCollection<tboperaciones>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptboperaciones;
                    }
                }
            }
        }
        private ICollection<tboperaciones> _tboperaciones;

        #endregion
        #region Association Fixup
    
        private void Fixuptboperaciones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tboperaciones item in e.NewItems)
                {
                    item.tbventa = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tboperaciones item in e.OldItems)
                {
                    if (ReferenceEquals(item.tbventa, this))
                    {
                        item.tbventa = null;
                    }
                }
            }
        }

        #endregion
    }
}
